import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import Header from "../compenents/Header";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../compenents/ui/card";
import { Suspense } from "react";
import Loading from "../loading";

const Home = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>aaa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center">
        <div className="flex gap-3 p-10">
          {user.isSignedIn ? (
            <Card>
              <CardHeader>
                <CardTitle>Card Title</CardTitle>
                <CardDescription>Card Description</CardDescription>
              </CardHeader>
              <CardContent>
                <Suspense fallback={<Loading />}>
                  <img
                    className="rounded-lg"
                    src="https://source.unsplash.com/random/400x200"
                    alt=""
                  />
                </Suspense>
              </CardContent>
              <CardFooter>
                <p>Card Footer</p>
              </CardFooter>
            </Card>
          ) : null}
        </div>
      </main>
    </>
  );
};

export default Home;
