import Head from "next/head";
import { SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Link from 'next/link';


const Home = () => {

  const user = useUser();
  const { data } = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="p-4 flex justify-between gap-2">
        <UserButton />
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
      </nav>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="flex gap-3">
          <ul>
            {data?.map((post) => (
              <li key={post.id}>{post.content}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
